---
title: "About this blog"
description: |
  Covid-19 : the menace to the global community in an era when homosapiense is boasting its technological superiority. I also joined the league of those researchers who are on a mission to find some insight that might help the global community to face the menace the better way scientifically.


---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



## Covid-19 Data Collection

Live and historical data available in public domain on Covid-19 of the United Kingdom are explored.

### Data description

```{css, echo = FALSE}
.fill {
  color: #69b6f0;
  font-size: 17px;
}
h2 {
  color: #006DAE;
}
h1 {
  display: block;
  font-size: 2em;
  margin-top: 0.67em;
  margin-bottom: 0.67em;
  margin-left: 0;
  margin-right: 0;
  font-weight: bold;
}
```

Dataset is collected from Joachim Gassen's [[**Github-repository**]{.fill}](https://github.com/joachim-gassen/tidycovid19)

The data is updated on a daily basis.



```{r echo = FALSE, warning = FALSE,message=FALSE}
library(tidyverse)
library(tidycovid19)
library(zoo)
library(plotly)
library(kableExtra)
df <- tidycovid19_variable_definitions %>%
  select(var_name, var_def)
kable(df) %>% kableExtra::kable_styling()
```



