---
title: "Egypt Covid-19 Information"
description: |
  An Insight on live data of Egypt
author:
  - name: Arpan Sarkar
date: 09-15-2021
output:
  distill::distill_article:
    self_contained: false
    toc: True
categories:
  - GGplot
  - Plotly
  - stats
  - highcharts
  - highcharter
  - time-series
  - data-visualization
---
```{r global, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      cache=TRUE, 
                      message =FALSE, 
                      warning=FALSE)
```

```{r}
library(tidyverse)
library(tidycovid19)
library(zoo)
library(plotly)
library(ggforce)
library(patchwork)
library(ggtext)
library(sparkline)
library(DT)
library(summarytools)
library(highcharter)
library(kableExtra)
library(lubridate)
library(gt)
library(formattable)
```

```{r}
df <- download_merged_data(cached = TRUE, silent = TRUE)

e<-df %>%
  filter(iso3c == "EGY") %>%
  mutate(
    new_cases = confirmed - lag(confirmed),
    ave_new_cases = rollmean(new_cases, 7, na.pad=TRUE, align="right"),
  new_deaths = deaths-lag(deaths), ave_new_deaths= rollmean(new_deaths, 7, na.pad=TRUE, align="right") ) %>%
  filter(!is.na(new_cases), !is.na(ave_new_cases)) %>%
  filter(!is.na(new_deaths), !is.na(ave_new_deaths))%>%
  ggplot(aes(x = date)) +
          
  labs(y="New cases and deaths")+
  geom_bar(aes(y = new_cases), stat = "identity", fill = "lightblue") +
  geom_line(aes(y = ave_new_cases), color ="orange") +
  geom_line(aes(y= new_deaths), color ="red")+
  theme(axis.text.x = element_text(angle=75))+
  theme_minimal()

ggplotly(e)
```




```{r}
df <- download_merged_data(cached = TRUE, silent = TRUE)

  EGY<- df %>%filter(iso3c == "EGY")
  
  EGY_wide<- EGY %>%  mutate(new_cases = confirmed - lag(confirmed), new_deaths= deaths-lag(deaths),new_vaccination = total_vaccinations - lag(total_vaccinations), new_recovered= recovered- lag(recovered), new_tests= total_tests- lag(total_tests),Month_yr=format_ISO8601(EGY$date, precision = "ym"),vaccination_pcnt=(total_vaccinations/(2*population)*100))%>%filter(new_recovered != -232179)%>% group_by(Month_yr)%>% summarise( new_cases= sum(new_cases,na.rm = T), new_deaths=sum(new_deaths, na.rm = T),new_vaccination=sum(new_vaccination, na.rm = T), new_recovered=sum(new_recovered, na.rm = T), new_tests= sum(new_tests)) 

EGY1<-EGY_wide%>%filter(new_recovered != -232179, Month_yr>'2020-03') 


 highchart() %>% 
    hc_chart(type = "column") %>%
    hc_xAxis(categories = EGY1$Month_yr) %>%
    hc_add_series(name="New cases",data = round(EGY1$new_cases),color='#fcba03') %>%
  hc_add_series(name="New Deaths",data = EGY1$new_deaths, color='#800303') %>%
   hc_add_series(name="New Recoveries",data = EGY1$new_recovered)
```



```{r covdf1,layout = "l-body-outset"}
covdf <- df %>% 
  filter(date == "2021-08-30") %>% 
  filter(region == "Middle East & North Africa") %>% 
  select(c(`country`,`confirmed`,`deaths`,`population`,`total_vaccinations`)) %>% 
  mutate(confirmed = as.double(confirmed),
         death_rate = (deaths/confirmed)*100,
         vaccinationpcnt=((total_vaccinations)/(2*population))*100) %>%
  
  relocate(death_rate, .before = population) %>%
  arrange(desc(confirmed)) 
covdf$population[19]<-2807.0000
covdf$population[20]<-1343.2700
covdf1 <- covdf %>% 
  select(-`deaths`) %>% 
  mutate(Rank = 1:nrow(covdf)) %>% 
  relocate(Rank, .before = country) %>% 
  mutate(death_rank = order(order(death_rate, decreasing = T))) %>% 
  relocate(death_rank, .before = population) %>%
  mutate(population_rank = order(order(population, decreasing = T))) %>% 
  rename(population = `population`) %>% 
  relocate(vaccinationpcnt, .after = population_rank) %>% 
  rename(Vax_Percentage = vaccinationpcnt) %>% 
  rename(New_cases = confirmed )%>%
  mutate(across(is.numeric, ~round(.,3)))
covdf1$country[6]<-"UAE"
covdf1$country[11]<-"PSE"
covdf1$total_vaccinations[14]<- 10769834
covdf1$Vax_Percentage[14]<- (10769834/102334403)*100
library(formattable)
formattable(covdf1, list(
    New_cases = color_tile("#ffe59c","#f5b642"),
    death_rate = color_tile("transparent", "#e04c65"),
    population = color_tile("#fc6958","#ff0000"),
    total_vaccinations = color_tile("#8ee693","#27962d"),
    Vax_Percentage = color_tile("transparent","#27962d")
    ),
    align = "c",
    caption = "Covid19 situation in middle-east countries")%>%scroll_box(width = "660px", height = "400px")
```

```{r}

EGY_wide1<- EGY %>%  mutate(new_cases = confirmed - lag(confirmed), new_deaths= deaths-lag(deaths),new_vaccination = total_vaccinations - lag(total_vaccinations), new_recovered= recovered- lag(recovered), new_tests= total_tests- lag(total_tests),Month_yr=format_ISO8601(EGY$date, precision = "ym"),vaccination_pcnt=(total_vaccinations/(2*population)*100))%>%select(Month_yr,new_tests,new_cases,new_deaths,new_vaccination,new_recovered,deaths,total_vaccinations,vaccination_pcnt)

```




```{r}
EGY_wide1%>%filter(Month_yr>"2021-02")%>%
  
hchart(type = "bar", hcaes(x = Month_yr , y = round(vaccination_pcnt, digits = 3),color=c("#009107")))%>% hc_yAxis(title = list(text = "Percentage Of Vaccination"),
         
         plotLines = list(
           list(label = list(text = ""),
                color = "red",
                width = 2,
                value = 50)))
```



```{r}
EGY_wide1%>%
  
hchart(type = "bar", hcaes(x = Month_yr , y = new_deaths,color=c("#870000")))%>% hc_yAxis(title = list(text = "Death Cases"),
         
         plotLines = list(
           list(label = list(text = ""),
                color = "red",
                width = 2,
                value = 50)))

```












