---
title: "my-2nd-post"
description: |
  A short description of the post.
author:
  - name: Arpan Sarkar
    url: {}
date: 09-02-2021
output:
  distill::distill_article:
    self_contained: false
---

```{css, echo = FALSE}
.fill {
  color: red;
  font-weight: bold;
}
h2 {
  color: #006DAE;
}

.fill1 {
  color: #c41244;
  font-weight: normal;
}

.fill2 {
  color: #1c2aad;
  font-weight: normal;
}


```


```{css, echo = FALSE}

.btn {
  background-color: DodgerBlue;
  border: none;
  color: white;
  padding: 12px 30px;
  cursor: pointer;
  font-size: 20px;
}

.btn:hover {
  background-color: RoyalBlue;
}

```






```{r echo = FALSE, warning = FALSE,message=FALSE}
library(highcharter)
library(tidyverse)
library(tidycovid19)
library(zoo)
library(plotly)
library(ggforce)
library(patchwork)
library(ggtext)

df <- download_merged_data(cached = TRUE, silent = TRUE)

gbr<-df %>%
  filter(iso3c == "GBR")

gbr_wide<- gbr %>%  mutate(new_cases = confirmed - lag(confirmed), new_deaths= deaths-lag(deaths),new_vaccination = total_vaccinations - lag(total_vaccinations), new_recovered= recovered- lag(recovered), new_tests= total_tests- lag(total_tests))%>%filter(date>"2021-05-01" & date<"2021-09-01")%>%select(date,new_tests,new_cases,new_deaths,new_vaccination,new_recovered)

gbr_new<-gbr %>%  mutate(new_cases = confirmed - lag(confirmed), new_deaths= deaths-lag(deaths),new_vaccination = total_vaccinations - lag(total_vaccinations), new_recovered= recovered- lag(recovered), new_tests= total_tests- lag(total_tests))%>%pivot_longer(cols = c("new_cases","new_deaths","new_vaccination","new_recovered","new_tests"), names_to = "variable", values_to = "value")%>% select(date,country, variable,value,hosp_patients,icu_patients)

hchart(gbr_new, "line", 
  hcaes(x = date, y = value, group = variable)
  )

```

```{r echo = FALSE, warning = FALSE,message=FALSE}
library(gt)

gt(gbr_wide%>%head(7)) %>% 
  tab_header(title = "Covid-19 UK Data",
             subtitle = "Updated data is from last seven days") %>% 
  tab_source_note(md("Source: Dataset is collected from Joachim Gassen Github-repository")) %>% 
  cols_label(
    new_tests= html("new tests"),
    new_cases = html("new cases"),
    new_deaths = html("deaths"),
    new_vaccination = html("vaccine doses"),
    new_recovered = html("recovered<br>patients")
  )
```


<a href="https://assets.giftcardsuite.com/valentinesday/Valentines-Day-Theme-1.png" download>Click here</a> to download
